### ISSUE TITLE
Javascript error for italian translation

### ISSUE THREAD

**Issue by giosueDelgado** [Alanaktion/phproject#306] opened 2017-04-30 22:35 UTC
When I use the italian translation the javascript give me a "SyntaxError". You can correct the error by editing the file it.ini and replacing the character ' with \'

**Comment by Alanaktion** [comment] 2017-05-02 15:18
I'm unable to reproduce this error with the current code. Which page are you seeing the error on?

**Comment by giosueDelgado** [comment] 2017-05-02 17:07
If you set the Italian language and go to one Project.
If you click on history you get the error.

I fixed it replacing on the file it.ini the character
`'` with `\'`

**Comment by Alanaktion** [comment] 2017-05-02 21:28
Okay, we had a fix in place for that but it was not included in a release yet. Version [1.5.1](https://github.com/Alanaktion/phproject/releases/tag/v1.5.1) includes a fix for this issue.

**Closed by Alanaktion** 2017-05-02 21:28 UTC
Labels: bug, duplicate
