### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by optico** [Alanaktion/phproject#371] opened 2019-06-10 10:16 UTC
I get an blank page when I go to the install page. So I can't install it. Plz help thnx

**Comment by Alanaktion** [comment] 2019-06-21 04:14
Have you checked for any errors in your server error log? Most likely, you are missing one of the required PHP extensions.

**Comment by Citydampf** [comment] 2019-06-25 22:36
also config.php under app/model is missing in download zip file (last version).

**Comment by Alanaktion** [comment] 2019-06-27 04:17
Not sure if that was the cause of this issue, but @Citydampf that should be fixed now.

**Closed by Alanaktion** 2019-06-27 04:17 UTC
Labels: question
