### ISSUE TITLE
Adding a New Task at the Taskboard fails

### ISSUE THREAD

**Issue by steinhmor** [Alanaktion/phproject#148] opened 2015-11-06 22:34 UTC
![bildschirmfoto vom 2015-11-06 23 31 24](https://cloud.githubusercontent.com/assets/11630531/11010416/e4193fe6-84de-11e5-9272-793a0b23fae4.png)

**Comment by Alanaktion** [comment] 2015-11-07 18:05
I can't seem to reproduce this issue. Are you getting any errors in the Network tab of your browser's Developer Tools? Any messages there could be helpful in fixing this.

**Comment by steinhmor** [comment] 2015-11-07 20:11
it looks like there are no issues. 
![bildschirmfoto vom 2015-11-07 21 06 46](https://cloud.githubusercontent.com/assets/11630531/11017072/f263c610-8593-11e5-8657-02f7fdd16762.png)

editing and saving some already existing items in the taskboard seems to work.

**Comment by astahovn** [comment] 2015-11-08 09:57
@steinhmor Try to look at the php error log or apache log. Response with 500 status code most likely wouldn't show any error to client.

**Comment by steinhmor** [comment] 2015-11-10 00:29
error log:
[Tue Nov 10 01:27:26 2015] [error] [client xxx] HTTP 404 (GET /taskboard/2/img/ajax-loader.gif), referer: http://xxx/taskboard/2/me
[Tue Nov 10 01:27:26 2015] [error] [client xxx]  must be either int or array., referer: http://xxx/taskboard/2/me

**Comment by steinhmor** [comment] 2015-11-17 00:04
did the error log help?

**Comment by Alanaktion** [comment] 2015-11-17 00:19
It looks like this issue was specific to release v1.2.0, and was fixed in `master` shortly after the change. Try installing [v1.2.1](https://github.com/Alanaktion/phproject/releases/tag/v1.2.1) and let me know if it fixes the issue.

**Comment by steinhmor** [comment] 2015-11-17 19:53
seems to work

**Comment by Alanaktion** [comment] 2015-11-18 00:48
Awesome. Thanks for reporting this!

**Closed by Alanaktion** 2015-11-18 00:48 UTC
Labels: bug
